### ISSUE TITLE
bug: full freeze of Neovim on file reload

### ISSUE THREAD

**Issue by emersonford** [LazyVim/LazyVim#1581]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 & 0.9.2

### Operating system/version

Linux & macOS Sonoma

### Describe the bug

I've been experiencing what effectively feels like a deadlock on file reloads after updating to the latest version of LazyVim. I'm fairly confident this is due to LazyVim as I am able to consistently reproduce the issue with:
```
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins", commit = "f1ce07510d2048e33fec2b609814d68a7175d591" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  ...
})
```

but am not able to reproduce the issue when I use the immediate previous commit `364bcf325d91a06e6bd6516bdfed84399566cdb6`.

I've been trying to get a sense of what exactly is triggering this deadlock-like behavior, but haven't had much luck. The farthest I've gotten is using:
```
debug.sethook(function()
        local file = io.open("/home/emersonford/Downloads/nvim_bt", "a")
        file:write(debug.traceback("backtrace"))
        file:close()
end, "c", 43)
```

which spits out a file dominated by the following callstack:
```
/usr/share/nvim/runtime/lua/vim/treesitter/_fold.lua:190: in function 'get_folds_levels'
/usr/share/nvim/runtime/lua/vim/treesitter/_fold.lua:249: in function 'fn'
/usr/share/nvim/runtime/lua/vim/treesitter/_fold.lua:236: in function </usr/share/nvim/runtime/lua/vim/treesitter/_fold.lua:232
```

I do see a comment about infinite recursion here: https://github.com/neovim/neovim/blob/1e7e9ee91f73c62b8c5ba9dbdabba3a3b6dc0130/runtime/lua/vim/treesitter/_fold.lua#L280

not sure if this is related?

### Steps To Reproduce

1. Open a file with formatting issues.
2. Run formatter outside of Neovim (e.g. `cargo fmt` in a separate tmux pane).
3. Neovim should now be completely unresponsive, only way to quit Neovim is with `kill -9`.

### Expected Behavior

Neovim should not freeze.

**Comment by folke** [comment]
This it not a LazyVim issue.
Might be related to this setting: `vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"`.

Report an issue upstream if that's what's causing it.

**Comment by davidsteinberger** [comment]
I just ran into the same. It is indeed caused/realted to value of `vim.opt.foldmethod`.
Setting this to `vim.opt.foldmethod = "manual"` in _options.lua_ fixes it for me at the expense of not having folds. 
How do others deal with that?

**Comment by folke** [comment]
It's clearly a bug.
Make sure to report an issue in the Neovim repo. I can't reproduce this.

**Comment by folke** [comment]
Can you try to see if Nightly solved this? If so I will change the defaults so that it only is enabled on nightly.

@delice0 same for you

**Comment by fredrikaverpil** [comment]
FWIW, I've been experiencing freezes today as well, but I'm not at my computer at the moment.

**Comment by folke** [comment]
This seems to have been fixed in this PR: https://github.com/neovim/neovim/pull/24230#issuecomment-1616684133

**Comment by folke** [comment]
If someone can confirm it works on nightly, then I'll just disable the feature for now on `0.9.x`

**Comment by folke** [comment]
@fredrikaverpil are you on 0.9.2 or a recent nightly?

**Comment by Delice0** [comment]
> vim.opt.foldmethod = "manual"

I'm not sure what "nightly" means in this context, but `vim.opt.foldmethod = "manual"` fixed it for me for now.

**Comment by folke** [comment]
That's not a fix. With nightly I mean on Neovim nightly. So a recent NEovim build.

**Comment by fredrikaverpil** [comment]
> @fredrikaverpil are you on 0.9.2 or a recent nightly?

0.9.2

**Comment by folke** [comment]
@jyuan0 and you get freezes on 0.9.2 as well?

I can't reproduce it on either at the moment.

**Comment by jyuan0** [comment]
> @jyuan0 and you get freezes on 0.9.2 as well?
Sorry, I don't have a build of 0.9.2 handy for testing.

**Comment by kingedward35** [comment]
I also experience the same issue and I am on 0.9.2.

**Comment by kingedward35** [comment]
I don't know if this will help, but I can see the issue after I update to the latest version of LazyVim and then restart NeoVim and open a file. I don't see it when the splash screen shows up upon opening, but only when I open a file. Hope that helps. And thanks.

**Comment by folke** [comment]
I just pushed a changed to enable treesitter folding only on 0.10

**Comment by kevintraver** [comment]
Working again in 0.9.2

Still freezes in 0.10

Specifically when opening telescope symbols `require("telescope.builtin").lsp_document_symbols()` in a larger file (5000 lines)

**Comment by folke** [comment]
just tested with a 12000 lines lua file and have no issues

**Comment by davidsteinberger** [comment]
@folke here's a repro that breaks for me up on nvim 0.9.2.

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
	spec = {
		-- add LazyVim and import its plugins
		{ "LazyVim/LazyVim", commit = "3849e0150b0a616dbd6e7e12ec5025aff6c81d39", import = "lazyvim.plugins" },
		-- { "LazyVim/LazyVim", commit = "d989ecc943b3240db0be3aa0369b96089cee4b40", import = "lazyvim.plugins" },
		-- import any extras modules here
		{ import = "lazyvim.plugins.extras.lang.typescript" },
	},
})
```

```bash
echo '{}' > test.json
nvim -u repro.lua test.json
```
Then in Lazyvim execute command `:e`.

**Comment by folke** [comment]
Great, thanks! I can reproduce this on `0.9.2`.

It works correctly on `0.10.0`, so all good :)

**Comment by dannyfritz** [comment]
Probably not the most useful comment, but I was dealing with this at work today and was just logging on now to report it. Glad to see it is sorted out already. I tested LazyVim 9.0.2 on Neovim 0.9.2 and can also confirm all is well here. :)

**Comment by clason** [comment]
Pro tip: not reporting bugs ensures that they will never be fixed (or the fix backported, in this case).

**Comment by folke** [comment]
Right, didn't think about backporting. Thanks!

**Comment by GitMurf** [comment]
> just tested with a 12000 lines lua file and have no issues

@folke I believe this treesitter fold expression bug has appeared in another (related) scenario. It is happening for me whenever switching to a buffer that has a filetype that treesitter does not have a parser for.

Steps to reproduce are explained in more detail here (https://github.com/echasnovski/mini.nvim/issues/1151#issuecomment-2308453218) but have also included the TLDR below:

1. Set `vim.opt.foldmethod = 'expr'` and `vim.opt.foldexpr = 'v:lua.vim.treesitter.foldexpr()'`
2. Create a new buf with `enew`
3. Add a couple thousand arbitrary lines of text into the buffer
4. Set the filetype for the buf to anything "random" that would not have a parser. In the original issue I was having it was for `minifiles` type => `set filetype=minifiles`
5. Create another new buffer (or open any buffer just to switch away from the buffer created above)
6. `bn` back to the buffer in question and you should notice a little pause/lag as it switches (the more lines, the more lag).
7. If you were to do verbose logging you would see thousands of log items for "searching for parsers" in every plugin location and repeated over and over for the number of lines in your buffer (plugin count * lines in buffer = number of checks for a parser file it does)

Let me know if you have any questions and/or if anyone else is able to reproduce?

Thanks!

**Comment by clason** [comment]
Please open a new issue with full context and reproduction steps.

**Comment by GitMurf** [comment]
> Please open a new issue with full context and reproduction steps.

@clason do you think I should open this up:

- here in LazyVim (probably not)?
- or in core Neovim (given the PR referenced earlier in this thread neovim/neovim/pull/24230)?
- or in Treesitter repo?

Thanks!

**Comment by clason** [comment]
If you can reproduce this without any plugins, then Neovim -- otherwise the plugin you cannot reproduce without. Definitely not tree-sitter.

**Comment by echasnovski** [comment]
@GitMurf, @clason, the core of the issue seems to be a juxtaposition of these issues:
- The `foldexpr` is evaluated for every line even if window has `nofoldenable`. Seems strange.
- The `foldexpr=v:lua.vim.treesitter.foldexpr()` keeps looking for parser for every line even if there is no tree-sitter parsing enabled in the buffer. Somewhat strange, but understandable.

Here are the steps without plugins and the need for thousands of lines:
- Create 'folds-ts.lua' file with the following content:
    ```lua
    vim.o.foldenable = false
    vim.o.foldmethod = 'expr'
    vim.o.foldexpr = 'v:lua.vim.treesitter.foldexpr()'

    vim.api.nvim_set_current_buf(vim.api.nvim_create_buf(true, false))

    local buf_id = vim.api.nvim_create_buf(true, false)
    vim.bo[buf_id].filetype = 'hello'
    vim.api.nvim_buf_set_lines(buf_id, 0, -1, false, { 'Line 1', 'Line 2', 'Line 3' })

    vim.o.verbose = 16
    vim.o.verbosefile = './nvim.log'
    ```
- `nvim -u folds-ts.lua`
- `:bnext`
- Inspect the './nvim.log' files. It contains three blocks of "Searching for "parser/hello.*" in runtime path", one for each line in the buffer.

This is both on 0.10.1 and latest `master`.

**Comment by clason** [comment]
Neovim issue then. But see https://github.com/neovim/neovim/pull/27422, which should resolve the _actual_ issue (slowdown).

**Comment by echasnovski** [comment]
> But see [neovim/neovim#27422](https://github.com/neovim/neovim/pull/27422), which should resolve the _actual_ issue (slowdown).

Sure, it'll make it better. But I am still puzzled as to why 'foldexpr' is evaluated even if 'nofoldenable' is set. Maybe I am misunderstanding what the latter means by "When off, all folds are open.".

**Comment by clason** [comment]
What it says on the tin: it doesn't _show_ folds, but doesn't disable the folding calculation (it's meant to be flipped on and off, so purely for presentation).

**Comment by GitMurf** [comment]
> the core of the issue seems to be a juxtaposition of these issues:

@echasnovski I have one more to add to your list. That is the fact that the problem occurs when there is a filetype that Treesitter does not have a parser for. So if Treesitter cannot find a parser, then it should not be checking "n" times for every line in the file. It should only have to check once, see there is no treesitter parser for that filetype and then NOT check again over and over for each line.

cc @clason

**Comment by clason** [comment]
Yes yes, that's exactly what the PR I linked is about.

**Comment by GitMurf** [comment]
Oh I see that PR 27422 actually explains almost exactly what I added above ;)

So given that PR already addresses my issue, is there a need to open a new issue?

Naturally the next question is, do we know what is holding up that PR? ;-)
