### ISSUE TITLE
bug: in basedpyright inlayHints config

### ISSUE THREAD

**Issue by victorkamoto** [LazyVim/LazyVim#4381]
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-11+g4c0d18c19

### Operating system/version

Arch latest

### Describe the bug

After using the python extra and setting `vim.g.lazyvim_python_lsp = "basedpyright"` in options.lua, the following error is triggered on every keypress.

`basedpyright: -32603: Request textDocument/inlayHint failed with message: Cannot read properties of undefined (reading 'tokenizerOutput')`

### Steps To Reproduce

1. Use python extra
2. Set  `vim.g.lazyvim_python_lsp = "basedpyright"`
3. Use lsp

### Expected Behavior

No errors

### Repro

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
  ui = {
    border = "rounded",
    backdrop = 100,
  },
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- import any extras modules here
    { import = "lazyvim.plugins.extras.coding.codeium" },
    { import = "lazyvim.plugins.extras.ui.treesitter-context" },
    { import = "lazyvim.plugins.extras.lang.json" },
    { import = "lazyvim.plugins.extras.ui.mini-animate" },
    { import = "lazyvim.plugins.extras.dap.core" },
    { import = "lazyvim.plugins.extras.coding.yanky" },
    { import = "lazyvim.plugins.extras.linting.eslint" },
    { import = "lazyvim.plugins.extras.formatting.prettier" },
    { import = "lazyvim.plugins.extras.lang.tailwind" },
    { import = "lazyvim.plugins.extras.lang.docker" },
    { import = "lazyvim.plugins.extras.lang.go" },
    { import = "lazyvim.plugins.extras.lang.clangd" },
    { import = "lazyvim.plugins.extras.lang.cmake" },
    { import = "lazyvim.plugins.extras.lang.rust" },
    { import = "lazyvim.plugins.extras.lang.python" },
    { import = "lazyvim.plugins.extras.formatting.black" },
    { import = "lazyvim.plugins.extras.lang.java" },
    { import = "lazyvim.plugins.extras.test.core" },
    { import = "lazyvim.plugins.extras.editor.outline" },
    { import = "lazyvim.plugins.extras.util.dot" },
    { import = "lazyvim.plugins.extras.editor.harpoon2" },
    { import = "lazyvim.plugins.extras.util.project" },
    { import = "lazyvim.plugins.extras.util.mini-hipatterns" },
    { import = "lazyvim.plugins.extras.lang.typescript" },
    { import = "lazyvim.plugins.extras.lang.svelte" },
    { import = "lazyvim.plugins.extras.lang.vue" },
    -- import/override with your plugins
    { import = "plugins" },
  },
  defaults = {
    -- By default, only LazyVim plugins will be lazy-loaded. Your custom plugins will load during startup.
    -- If you know what you're doing, you can set this to `true` to have all your custom plugins lazy-loaded by default.
    lazy = false,
    -- It's recommended to leave version=false for now, since a lot the plugin that support versioning,
    -- have outdated releases, which may break your Neovim install.
    version = false, -- always use the latest git commit
    -- version = "*", -- try installing the latest stable version for plugins that support semver
  },
  install = { colorscheme = { "tokyonight", "habamax" } },
  checker = { enabled = false }, -- automatically check for plugin updates
  performance = {
    rtp = {
      -- disable some rtp plugins
      disabled_plugins = {
        "gzip",
        -- "matchit",
        -- "matchparen",
        -- "netrwPlugin",
        "tarPlugin",
        "tohtml",
        "tutor",
        "zipPlugin",
      },
    },
  },
})
```

**Comment by dpetka2001** [comment]
This is an upstream issue in basedpyright. See https://github.com/DetachHead/basedpyright/issues/638

Not a LazyVim bug.

**Comment by victorkamoto** [comment]
Closing this as it has been fixed in upstream with release 1.17.3

**Comment by simondoesstuff** [comment]
I am still having this issue. It will take time to create a MRE, but

basedpyright 1.28.4
(based on pyright 1.1.398)
NVIM v0.11.0
using nixvim:  commit d4dada282aeac94b5d53dd70e276a2f5f534f783

The issue is related to the `pyproject.toml` config option:
```yml
[tool.pyright]
executionEnvironments = [
  { root = "src" },
]
```

**Comment by dpetka2001** [comment]
The issue here was never a Lazyvim issue to begin with. It was a issue with the LSP server itself. So create an issue at the LSP server. Not gonna be solved here. And nixvim is not Lazyvim, so it's not supported here.

**Comment by simondoesstuff** [comment]
> The issue here was never a Lazyvim issue to begin with. It was a issue with the LSP server itself. So create an issue at the LSP server. Not gonna be solved here. And nixvim is not Lazyvim, so it's not supported here.

Yep sorry, thought I was in the lsp repo.
