### ISSUE TITLE
bug: failed to run `config` for bufferline.nvim

### ISSUE THREAD

**Issue by chronon** [LazyVim/LazyVim#6355]
### Did you check docs and existing issues?

- [x] I have read all the LazyVim docs
- [x] I have updated the plugin to the latest version before submitting this issue
- [x] I have searched the existing issues of LazyVim
- [x] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.3

### Operating system/version

MacOS 15.6

### Describe the bug

A recent update [#920](https://github.com/catppuccin/nvim/pull/920) to the catppuccin nvim colorscheme produces a LazyVim error on launch:
```
Failed to run `config` for bufferline.nvim

...re/nvim/lazy/LazyVim/lua/lazyvim/plugins/colorscheme.lua:61: attempt to call field 'get' (a nil value)

# stacktrace:
  - /LazyVim/lua/lazyvim/plugins/colorscheme.lua:61 _in_ **values**
```

![Image](https://github.com/user-attachments/assets/74cbadec-4c95-402d-b235-e08db8d17434)

I believe the fix is to change `get()` on line 61 of `colorscheme.lua` to `get_theme()`.

### Steps To Reproduce

1. Install LazyVim
2. Confirm the Catppuccin colorscheme is enabled and up to date
3. Launch nvim

### Expected Behavior

No error message.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
    -- add any other plugins here
  },
})
```

**Comment by dpetka2001** [comment]
#6354

**Comment by adityagandhi-86** [comment]
I am facing a similar issue, and the fix recommended worked for me

**Comment by dpetka2001** [comment]
Better give thumbs up to OP who created PR. Didn't do anything myself. I don't actually use the colorscheme, so was not even aware.

**Comment by fang2hou** [comment]
Add this to config until the PR merged.
```lua
	{
		"catppuccin/nvim",
		opts = function(_, opts)
			local module = require("catppuccin.groups.integrations.bufferline")
			if module then
				module.get = module.get_theme
			end
			return opts
		end,
	},
```

**Comment by JoNilsson** [comment]
Other option is to just pin to V1.10.0, and clean / update.
```lua
"catppuccin/nvim",
    ...
        tag = "v1.10.0", -- Pin to v1.10 to avoid a breaking change in V1.11 API
    ...
```

And [subscribe to watch the upstream PR](https://github.com/LazyVim/LazyVim/pull/6354) for merge which addresses the API change, and un-pin afterwards.

**Comment by Gez-Schegtel** [comment]
I fixed the issue by making a change in the file _`~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/colorscheme.lua`_

I've changed this...

```lua
    specs = {
      {
        "akinsho/bufferline.nvim",
        optional = true,
        opts = function(_, opts)
          if (vim.g.colors_name or ""):find("catppuccin") then
            opts.highlights = require("catppuccin.groups.integrations.bufferline").get()
          end
        end,
      },

```
To this...

```lua
    specs = {
      {
        "akinsho/bufferline.nvim",
        optional = true,
        opts = function(_, opts)
          if (vim.g.colors_name or ""):find("catppuccin") then
            opts.highlights = require("catppuccin.groups.integrations.bufferline").get_theme()
          end
        end,
      },
```

Apparently, the `get()` method needs to be replaced with `get_theme()`.

Hope it helps! 🤘🏻😎

**Comment by wigging** [comment]
If I manually change

```lua
opts.highlights = require("catppuccin.groups.integrations.bufferline").get()
```

to

```lua
opts.highlights = require("catppuccin.groups.integrations.bufferline").get_theme()
```

in `~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/colorscheme.lua`; is this going to screw up future automatic updates or will future updates just overwrite this?

**Comment by dpetka2001** [comment]
> in ~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/colorscheme.lua; is this going to screw up future automatic updates or will future updates just overwrite this?

`lazy.nvim` will complain that you've made changes in that directory and won't be able to update until you revert the changes you made. Or just delete the plugin and re-install it. You should avoid making changes in `~/.local/share/nvim/lazy/` directory.

**Comment by Gez-Schegtel** [comment]
> > in ~/.local/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/colorscheme.lua; is this going to screw up future automatic updates or will future updates just overwrite this?
> 
> `lazy.nvim` will complain that you've made changes in that directory and won't be able to update until you revert the changes you made. Or just delete the plugin and re-install it. You should avoid making changes in `~/.local/share/nvim/lazy/` directory.

I'm sorry, I didn't know that modifying that file would create a conflict with the update system. 

I restored the file colorscheme.lua and tried this in the plugin `~/.config/nvim/lua/plugins/catppuccin.lua` and it seems to work:

```python
return {
  -- Carga Catppuccin temprano
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    lazy = false,
    opts = {
      flavour = "mocha",
      background = { light = "latte", dark = "mocha" },
      auto_integrations = true,
      integrations = { bufferline = true },
    },
    -- Shim: si tu Catppuccin trae get_theme() pero no get(), creamos un alias
    init = function()
      local ok, mod = pcall(require, "catppuccin.groups.integrations.bufferline")
      if ok and mod and not mod.get and type(mod.get_theme) == "function" then
        mod.get = mod.get_theme
      end
    end,
  },

  -- Haz que LazyVim use Catppuccin por defecto
  {
    "LazyVim/LazyVim",
    opts = { colorscheme = "catppuccin" },
  },

  -- (Opcional) extra por si quieres tocar Bufferline desde tu config;
  -- aquí usamos lo que exista: get_theme() o get()
  {
    "akinsho/bufferline.nvim",
    optional = true,
    opts = function(_, opts)
      if (vim.g.colors_name or ""):find("catppuccin") then
        local ok, mod = pcall(require, "catppuccin.groups.integrations.bufferline")
        if ok then
          local get = mod.get_theme or mod.get
          if type(get) == "function" then
            opts.highlights = get({})
          end
        end
      end
    end,
  },
}
```

**Comment by dpetka2001** [comment]
You can just do as suggested in [this comment](https://github.com/LazyVim/LazyVim/issues/6355#issuecomment-3212986215). No need for all this.

**Comment by Gez-Schegtel** [comment]
> You can just do as suggested in [this comment](https://github.com/LazyVim/LazyVim/issues/6355#issuecomment-3212986215). No need for all this.

Oh, thank you!

**Comment by wigging** [comment]
When this is fixed, how do I run the update to apply the fix? Do I run LazyVim then go into lazy.nvim and choose update (`Shift + U`) to apply the update?

**Comment by chronon** [comment]
> When this is fixed, how do I run the update to apply the fix? Do I run LazyVim then go into lazy.nvim and choose update (`Shift + U`) to apply the update?

Yes, `<leader>l` then `S` (sync) or `U` (update) when a new LazyVim version is released.

**Comment by Deepfreeze20k** [comment]
fixed it for me, thanks a lot!

**Comment by folke** [comment]
fixed

**Comment by wigging** [comment]
@folke This is not fixed. I updated LazyVim and I still get this error.

**Comment by MikeVensel** [comment]
I also updated and found that the issue isn't fixed. The workaround posted continues to work though.

**Comment by dpetka2001** [comment]
The fix has been incorporated into latest HEAD. But a new LazyVim stable release has not been made yet. 

So, either you'll have to be a bit patient until a new LazyVim stable release is created or just follow HEAD according to the [docs](https://www.lazyvim.org/configuration/lazy.nvim).

**Comment by MikeVensel** [comment]
Oh ok. I didn't realize that was how it worked. I assumed that it was closed because it was available to everyone. Thanks for the clarification!

**Comment by dpetka2001** [comment]
FYI I just follow HEAD and don't have to wait until a new release is made. I haven't had a problem following HEAD. If you like you can also do that or not. The PR for the new stable release is #6422.

**Comment by naysonpedro25** [comment]
> "

this is the fast and best solution, thanks

**Comment by davidfmatheson** [comment]
This is fixed in the latest release, for those who didn't want to follow HEAD. Just verified.

**Comment by wigging** [comment]
> This is fixed in the latest release, for those who didn't want to follow HEAD. Just verified.

I can also confirm this has been fixed in latest release.

**Comment by jxuanli** [comment]
does this fix apply to nvim v0.11.4 (on ubuntu24)? fresh installed both nvim and lazyvim (even tried this within docker) and this is still happening

**Comment by log0z** [comment]
> does this fix apply to nvim v0.11.4 (on ubuntu24)? fresh installed both nvim and lazyvim (even tried this within docker) and this is still happening

I think you've encountered with an issue resolved by the following PR: https://github.com/LazyVim/LazyVim/pull/6505.
